### ISSUE TITLE
Question: reading ELF image from disk vs memory

### ISSUE THREAD

**Issue by ksurent** [DavidBuchanan314/dlinject#4]
Hi,

First of all, thanks for putting this example together and documenting it.

I've been fooling around with injecting code on my own and in my experiments I've faced an issue that I can't seem to explain yet. What I found interesting is that you've chosen a different approach and I'm wondering if you could elaborate on why. Here goes.

In this project after reading the memory map, you're reading the actual shared library from disk. In my code I'm trying to read the library from the processes' memory by reading corresponding regions. However, what I'm seeing is that the resulting ELF image is corrupted (the headers section offset points past EOF). I'm wondering if you saw something similar and chose to fix/work around by reading from disk. If so, were you able to find an explanation as to why this was happening?

**Comment by DavidBuchanan314** [comment]
ELF files aren't just mapped into memory as-is, so there's no guarantee that what sits in memory is a valid ELF.

I chose to read from disk just because that felt like the simplest thing to do.

pwntools has something called [dynelf](https://docs.pwntools.com/en/stable/dynelf.html), which can be used to resolve symbols in an in-memory elf. Typically, you would use it in combination with a memory leak exploit, but of course in this case you can use `/proc/[pid]/mem`.

**Comment by ksurent** [comment]
I see. Must've missed something when I was skimming through the kernel's ELF loader code because I thought that files are just `mmap`-ed as is.

Thanks for replying! Feel free to close.
